version: '2'
services:
  node-app:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - node-app
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - node-app

networks:
  node-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
