version: '2'
services:
  api-server:
    build: ./
    env_file: ./config/config.env
    ports:
      - "3000:3000"
    networks:
      - node-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6-xenial
    environment:
      - MONGO_INITDB_DATABASE=notes
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - node-app

networks:
  node-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
